### ISSUE TITLE
PHP 8.1 - Implicit conversion from float

### ISSUE THREAD

**Issue by guisaldanha** [Moskito89/php-moon-phase#37]
Deprecated: Implicit conversion from float 2459168.989399461 to int loses precision in ... /MoonPhase.php on line 187

**Comment by Moskito89** [comment]
Hi @guisaldanha, thanks for reporting this. The deprecations comes under PHP 8.1. Please feel free to change the line and create a Pull Request. Thank you!

**Comment by Moskito89** [comment]
Closed by https://github.com/Moskito89/php-moon-phase/pull/38.
